name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  pull_request_target:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-11
    strategy:
      fail-fast: false
      matrix:
        xcode: ['Xcode_13.0']
    env:
      DEVELOPER_DIR: /Applications/${{ matrix.xcode }}.app/Contents/Developer

    steps:
    - uses: actions/checkout@v2
    - name: Build and Test
      run: set -o pipefail && xcodebuild -scheme FioriSwiftUI-Package -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11' clean build test
    - uses: actions/upload-artifact@v3
      name: "Upload Test Logs"
      if: ${{ always() }}
      with:
        name: test-logs
        path: |
          ~/Library/Developer/Xcode/DerivedData/cloud-sdk-ios-fiori-*/Logs/Test  
